const flagByCountry: Record<string, string> = {
  Spain: '🇪🇸',
  France: '🇫🇷',
  Germany: '🇩🇪',
  'United States of America': '🇺🇸',
  Brazil: '🇧🇷',
  China: '🇨🇳',
  Japan: '🇯🇵',
  Australia: '🇦🇺',
  Canada: '🇨🇦',
  Mexico: '🇲🇽',
  Argentina: '🇦🇷',
  Chile: '🇨🇱',
  'United Kingdom': '🇬🇧',
  India: '🇮🇳',
  Russia: '🇷🇺',
  'South Africa': '🇿🇦',
  Indonesia: '🇮🇩',
  'New Zealand': '🇳🇿',
  Colombia: '🇨🇴',
  Peru: '🇵🇪',
  Ecuador: '🇪🇨',
  Venezuela: '🇻🇪',
  Bolivia: '🇧🇴',
  Paraguay: '🇵🇾',
  Uruguay: '🇺🇾',
  'Costa Rica': '🇨🇷',
  Panama: '🇵🇦',
  Guatemala: '🇬🇹',
  Belize: '🇧🇿',
  Honduras: '🇭🇳',
  'El Salvador': '🇸🇻',
  Nicaragua: '🇳🇮',
  'Dominican Republic': '🇩🇴',
  Cuba: '🇨🇺',
  Jamaica: '🇯🇲',
  'Trinidad and Tobago': '🇹🇹',
  'Puerto Rico': '🇵🇷',
  Bahamas: '🇧🇸',
  Barbados: '🇧🇧',
  Dominica: '🇩🇲',
  'Saint Lucia': '🇱🇨',
  'Saint Vincent and the Grenadines': '🇻🇨',
  'Antigua and Barbuda': '🇦🇬',
  Grenada: '🇬🇩',
  'Saint Kitts and Nevis': '🇰🇳',
  'Saint Pierre and Miquelon': '🇵🇲',
  Greenland: '🇬🇱',
  Bermuda: '🇧🇲',
  Portugal: '🇵🇹',
  Italy: '🇮🇹',
  Netherlands: '🇳🇱',
  Belgium: '🇧🇪',
  Switzerland: '🇨🇭',
  Austria: '🇦🇹',
  Poland: '🇵🇱',
  Greece: '🇬🇷',
  Turkey: '🇹🇷',
  Sweden: '🇸🇪',
  Norway: '🇳🇴',
  Finland: '🇫🇮',
  Iceland: '🇮🇸',
  Ireland: '🇮🇪',
  Morocco: '🇲🇦',
  Algeria: '🇩🇿',
  Tunisia: '🇹🇳',
  Egypt: '🇪🇬',
  Nigeria: '🇳🇬',
  Ghana: '🇬🇭',
  Senegal: '🇸🇳',
  Kenya: '🇰🇪',
  Ethiopia: '🇪🇹',
  'Saudi Arabia': '🇸🇦',
  'United Arab Emirates': '🇦🇪',
  Iran: '🇮🇷',
  Pakistan: '🇵🇰',
  Thailand: '🇹🇭',
  Vietnam: '🇻🇳',
  Philippines: '🇵🇭',
  'South Korea': '🇰🇷',
  Singapore: '🇸🇬',
  Malaysia: '🇲🇾',
  Israel: '🇮🇱',
  Afghanistan: '🇦🇫',
  Nepal: '🇳🇵',
  Myanmar: '🇲🇲',
  Bangladesh: '🇧🇩',
  Ukraine: '🇺🇦',
  Taiwan: '🇹🇼',
  Romania: '🇷🇴',
  Hungary: '🇭🇺',
  'Czech Republic': '🇨🇿',
  Kazakhstan: '🇰🇿',
  Uzbekistan: '🇺🇿',
  Denmark: '🇩🇰',
  Croatia: '🇭🇷',
  Serbia: '🇷🇸',
  Slovakia: '🇸🇰',
  Slovenia: '🇸🇮',
  Bulgaria: '🇧🇬',
  Estonia: '🇪🇪',
  Latvia: '🇱🇻',
  Lithuania: '🇱🇹',
  'Sri Lanka': '🇱🇰',
  Cambodia: '🇰🇭',
  Qatar: '🇶🇦',
  Lebanon: '🇱🇧',
  Jordan: '🇯🇴',
  Iraq: '🇮🇶',
  Tanzania: '🇹🇿',
  Uganda: '🇺🇬',
  Sudan: '🇸🇩',
  Haiti: '🇭🇹',
  Fiji: '🇫🇯',
  Samoa: '🇼🇸',
  Tonga: '🇹🇴',
  Maldives: '🇲🇻',
  Seychelles: '🇸🇨',
  Mauritius: '🇲🇺',
  Malta: '🇲🇹',
  Cyprus: '🇨🇾',
  Luxembourg: '🇱🇺',
  Andorra: '🇦🇩',
  Monaco: '🇲🇨',
  'Cape Verde': '🇨🇻',
  Brunei: '🇧🇳',
  Bhutan: '🇧🇹',
  'Timor-Leste': '🇹🇱',
  Aruba: '🇦🇼',
  Curacao: '🇨🇼',
  Kiribati: '🇰🇮',
  'Papua New Guinea': '🇵🇬',
  Madagascar: '🇲🇬',
  Zimbabwe: '🇿🇼',
  Namibia: '🇳🇦',
  Botswana: '🇧🇼',
  Mongolia: '🇲🇳',
  Laos: '🇱🇦',
  Georgia: '🇬🇪',
  Armenia: '🇦🇲',
  Azerbaijan: '🇦🇿',
  Albania: '🇦🇱',
  'North Macedonia': '🇲🇰',
  'Bosnia and Herzegovina': '🇧🇦',
  Montenegro: '🇲🇪',
  Moldova: '🇲🇩',
  Belarus: '🇧🇾',
  Guyana: '🇬🇾',
  Suriname: '🇸🇷',
  Kuwait: '🇰🇼',
  Bahrain: '🇧🇭',
  Oman: '🇴🇲',
  Cameroon: '🇨🇲',
  Angola: '🇦🇴',
  Zambia: '🇿🇲',
  Rwanda: '🇷🇼',
  Syria: '🇸🇾',
  Yemen: '🇾🇪',
  Tajikistan: '🇹🇯',
  Kyrgyzstan: '🇰🇬',
  Turkmenistan: '🇹🇲',
  'Vatican City': '🇻🇦',
  'San Marino': '🇸🇲',
  Liechtenstein: '🇱🇮',
  Vanuatu: '🇻🇺',
  'Solomon Islands': '🇸🇧',
  Palau: '🇵🇼',
  Mozambique: '🇲🇿',
  Malawi: '🇲🇼',
  Mali: '🇲🇱',
  'North Korea': '🇰🇵',
  'Hong Kong': '🇭🇰',
  Macau: '🇲🇴',
  Gibraltar: '🇬🇮',
  'Marshall Islands': '🇲🇭',
  Micronesia: '🇫🇲',
  Nauru: '🇳🇷',
  Tuvalu: '🇹🇻',
  'Falkland Islands': '🇫🇰',
  'Cayman Islands': '🇰🇾',
  'British Virgin Islands': '🇻🇬',
  'US Virgin Islands': '🇻🇮',
  Libya: '🇱🇾',
  Somalia: '🇸🇴',
  Djibouti: '🇩🇯',
  Eritrea: '🇪🇷',
  Gabon: '🇬🇦',
  'Republic of the Congo': '🇨🇬',
  'Democratic Republic of the Congo': '🇨🇩',
  'Equatorial Guinea': '🇬🇶',
  Palestine: '🇵🇸',
  'Turks and Caicos Islands': '🇹🇨',
  'Cook Islands': '🇨🇰',
  Niue: '🇳🇺',
  'Sint Maarten': '🇸🇽',
  France_Overseas: '🇫🇷',
  // Más países y territorios
  'Western Sahara': '🇪🇭',
  Guadeloupe: '🇬🇵',
  Martinique: '🇲🇶',
  Réunion: '🇷🇪',
  Mayotte: '🇾🇹',
  Guernsey: '🇬🇬',
  Jersey: '🇯🇪',
  Isle_of_Man: '🇮🇲',
  Faroe_Islands: '🇫🇴',
  Svalbard: '🇸🇯',
  'Saint Barthelemy': '🇧🇱',
  'Saint Martin': '🇲🇫',
  'Wallis and Futuna': '🇼🇫',
  'French Guiana': '🇬🇫',
  'French Polynesia': '🇵🇫',
  'New Caledonia': '🇳🇨',
  'South Sudan': '🇸🇸',
  Eswatini: '🇸🇿',
  Lesotho: '🇱🇸',
  Guinea: '🇬🇳',
  Benin: '🇧🇯',
  Burkina_Faso: '🇧🇫',
  Togo: '🇹🇬',
  Niger: '🇳🇪',
  Chad: '🇹🇩',
  Central_African_Republic: '🇨🇫',
  Sierra_Leone: '🇸🇱',
  Liberia: '🇱🇷',
  Mauritania: '🇲🇷',
  Guinea_Bissau: '🇬🇼',
  Gambia: '🇬🇲',
  Western_Samoa: '🇼🇸',
  // Tonga, Kiribati y Tuvalu ya existen arriba, se eliminan duplicados
  'Saint Helena': '🇸🇭',
  Anguilla: '🇦🇮',
  Montserrat: '🇲🇸',
  'Saint Eustatius': '🇧🇶',
  Bonaire: '🇧🇶',
  'Sint Eustatius': '🇧🇶',
  Saba: '🇧🇶',
  'Heard Island and McDonald Islands': '🇭🇲',
  'Cocos (Keeling) Islands': '🇨🇨',
  'Christmas Island': '🇨🇽',
  Pitcairn: '🇵🇳',
  Tokelau: '🇹🇰',
  'South Georgia and the South Sandwich Islands': '🇬🇸',
  'British Indian Ocean Territory': '🇮🇴',
  'American Samoa': '🇦🇸',
  Guam: '🇬🇺',
  'Northern Mariana Islands': '🇲🇵',
  'US Minor Outlying Islands': '🇺🇲',
  'Antarctica': '🇦🇶',
};

export function getFlagEmoji(countryName: string) {
  return flagByCountry[countryName] ?? '🏳️';
}
