const flagByCountry: Record<string, string> = {
  Spain: '🇪🇸',
  France: '🇫🇷',
  Germany: '🇩🇪',
  'United States of America': '🇺🇸',
  Brazil: '🇧🇷',
  China: '🇨🇳',
  Japan: '🇯🇵',
  Australia: '🇦🇺',
  Canada: '🇨🇦',
  Mexico: '🇲🇽',
  Argentina: '🇦🇷',
  Chile: '🇨🇱',
  'United Kingdom': '🇬🇧',
  India: '🇮🇳',
  Russia: '🇷🇺',
  'South Africa': '🇿🇦',
  Indonesia: '🇮🇩',
  'New Zealand': '🇳🇿',
  Colombia: '🇨🇴',
  Peru: '🇵🇪',
  Ecuador: '🇪🇨',
  Venezuela: '🇻🇪',
  Bolivia: '🇧🇴',
  Paraguay: '🇵🇾',
  Uruguay: '🇺🇾',
  'Costa Rica': '🇨🇷',
  Panama: '🇵🇦',
  Guatemala: '🇬🇹',
  Belize: '🇧🇿',
  Honduras: '🇭🇳',
  'El Salvador': '🇸🇻',
  Nicaragua: '🇳🇮',
  'Dominican Republic': '🇩🇴',
  Cuba: '🇨🇺',
  Jamaica: '🇯🇲',
  'Trinidad and Tobago': '🇹🇹',
  'Puerto Rico': '🇵🇷',
  Bahamas: '🇧🇸',
  Barbados: '🇧🇧',
  Dominica: '🇩🇲',
  'Saint Lucia': '🇱🇨',
  'Saint Vincent and the Grenadines': '🇻🇨',
  'Antigua and Barbuda': '🇦🇬',
  Grenada: '🇬🇩',
  'Saint Kitts and Nevis': '🇰🇳',
  'Saint Pierre and Miquelon': '🇵🇲',
  Greenland: '🇬🇱',
  Bermuda: '🇧🇲'
};

export function getFlagEmoji(countryName: string) {
  return flagByCountry[countryName] ?? '🏳️';
}
